apiVersion: v2
name: q4
description: A Helm chart for Q4 application

# Change the version as you release new versions of your chart.
version: 0.1.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
# appVersion: "1.0.0"

type: application
