{{- if .Values.global.gatewayEnabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-http-route
spec:
  parentRefs:
    - name: {{ .Values.global.gatewayName | required "gatewayName is required" }}
      {{- if .Values.global.gatewayNamespace }}
      namespace: {{ .Values.global.gatewayNamespace }}
      {{- end }}
      sectionName: {{ .Values.global.gatewaySectionName | required "gatewaySectionName is required" }}
  hostnames:
    - {{ .Values.global.hostname | required "hostname is required" }}
  rules:
    - backendRefs:
        - name: {{ .Release.Name }}-service
          port: {{ .Values.ui.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /api
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: ""
      backendRefs:
        - name: {{ .Release.Name }}-service
          port: {{ .Values.api.port }}
{{- end }}
