apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.api.port }}
    - name: ui
      protocol: TCP
      port: {{ .Values.ui.port }}