// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for GetAuctionItemsParamsSortKey.
const (
	CurrentBid GetAuctionItemsParamsSortKey = "currentBid"
	EndTime    GetAuctionItemsParamsSortKey = "endTime"
	StartPrice GetAuctionItemsParamsSortKey = "startPrice"
	StartTime  GetAuctionItemsParamsSortKey = "startTime"
	Title      GetAuctionItemsParamsSortKey = "title"
)

// Defines values for GetAuctionItemsParamsSortOrder.
const (
	Asc  GetAuctionItemsParamsSortOrder = "asc"
	Desc GetAuctionItemsParamsSortOrder = "desc"
)

// ApiResponse defines model for ApiResponse.
type ApiResponse struct {
	Code    *int32  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// BidEvent defines model for BidEvent.
type BidEvent struct {
	Bid  uint32    `json:"bid"`
	Time time.Time `json:"time"`
	User string    `json:"user"`
}

// PostAuctionItemJSONBody defines parameters for PostAuctionItem.
type PostAuctionItemJSONBody struct {
	Carousels     *[]string  `json:"carousels,omitempty"`
	Description   *string    `json:"description,omitempty"`
	EndTime       time.Time  `json:"endTime"`
	StartTime     *time.Time `json:"startTime,omitempty"`
	StartingPrice *int64     `json:"startingPrice,omitempty"`
	Title         string     `json:"title"`
}

// PostAuctionItemParams defines parameters for PostAuctionItem.
type PostAuctionItemParams struct {
	// AccessToken access token for current user.
	AccessToken *string `form:"accessToken,omitempty" json:"accessToken,omitempty"`
}

// PostAuctionItemItemIDBidsJSONBody defines parameters for PostAuctionItemItemIDBids.
type PostAuctionItemItemIDBidsJSONBody struct {
	Bid uint32 `json:"bid"`
}

// PostAuctionItemItemIDBidsParams defines parameters for PostAuctionItemItemIDBids.
type PostAuctionItemItemIDBidsParams struct {
	// AccessToken access token for current user.
	AccessToken *string `form:"accessToken,omitempty" json:"accessToken,omitempty"`
}

// GetAuctionItemsParams defines parameters for GetAuctionItems.
type GetAuctionItemsParams struct {
	// Title Search term for filtering items.
	Title *string `form:"title,omitempty" json:"title,omitempty"`

	// StartPrice Starting price range for filtering items.
	StartPrice *struct {
		From *int `json:"from,omitempty"`
		To   *int `json:"to,omitempty"`
	} `json:"startPrice,omitempty"`

	// CurrentBid Current bid range for filtering items.
	CurrentBid *struct {
		From *int `json:"from,omitempty"`
		To   *int `json:"to,omitempty"`
	} `json:"currentBid,omitempty"`

	// StartTime The auction start time range for filtering items.
	StartTime *struct {
		From *time.Time `json:"from,omitempty"`
		To   *time.Time `json:"to,omitempty"`
	} `json:"startTime,omitempty"`

	// EndTime The auction end time range for filtering items.
	EndTime *struct {
		From *time.Time `json:"from,omitempty"`
		To   *time.Time `json:"to,omitempty"`
	} `json:"endTime,omitempty"`

	// Sort Sort criteria.
	Sort *struct {
		Key   *GetAuctionItemsParamsSortKey   `json:"key,omitempty"`
		Order *GetAuctionItemsParamsSortOrder `json:"order,omitempty"`
	} `json:"sort,omitempty"`

	// LastItemID The last item ID of the previous page.
	LastItemID *openapi_types.UUID `form:"lastItemID,omitempty" json:"lastItemID,omitempty"`

	// Size The maximum number of items to return.
	Size *uint32 `form:"size,omitempty" json:"size,omitempty"`

	// ExcludeEnded Exclude ended items.
	ExcludeEnded *bool `form:"excludeEnded,omitempty" json:"excludeEnded,omitempty"`
}

// GetAuctionItemsParamsSortKey defines parameters for GetAuctionItems.
type GetAuctionItemsParamsSortKey string

// GetAuctionItemsParamsSortOrder defines parameters for GetAuctionItems.
type GetAuctionItemsParamsSortOrder string

// GetAuthCallbackParams defines parameters for GetAuthCallback.
type GetAuthCallbackParams struct {
	// Code Authorization code.
	Code string `form:"code" json:"code"`

	// State Authorization state.
	State string `form:"state" json:"state"`

	// RedirectUrl Url to back after finishing authorization.
	RedirectUrl string `form:"redirect_url" json:"redirect_url"`

	// RequestState Stored authentication state.
	RequestState *string `form:"requestState,omitempty" json:"requestState,omitempty"`

	// RequestNonce Stored authentication nonce.
	RequestNonce *string `form:"requestNonce,omitempty" json:"requestNonce,omitempty"`
}

// GetAuthLoginParams defines parameters for GetAuthLogin.
type GetAuthLoginParams struct {
	// RedirectUrl Url to back after finishing authorization.
	RedirectUrl string `form:"redirect_url" json:"redirect_url"`
}

// GetAuthLogoutParams defines parameters for GetAuthLogout.
type GetAuthLogoutParams struct {
	// AccessToken access token for current user.
	AccessToken *string `form:"accessToken,omitempty" json:"accessToken,omitempty"`

	// Username name for current user.
	Username *string `form:"username,omitempty" json:"username,omitempty"`
}

// PostImageParams defines parameters for PostImage.
type PostImageParams struct {
	// AccessToken access token for current user.
	AccessToken *string `form:"accessToken,omitempty" json:"accessToken,omitempty"`
}

// PostAuctionItemJSONRequestBody defines body for PostAuctionItem for application/json ContentType.
type PostAuctionItemJSONRequestBody PostAuctionItemJSONBody

// PostAuctionItemItemIDBidsJSONRequestBody defines body for PostAuctionItemItemIDBids for application/json ContentType.
type PostAuctionItemItemIDBidsJSONRequestBody PostAuctionItemItemIDBidsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Add a new auction item
	// (POST /auction/item)
	PostAuctionItem(c *gin.Context, params PostAuctionItemParams)
	// Get auction item details
	// (GET /auction/item/{itemID})
	GetAuctionItemItemID(c *gin.Context, itemID openapi_types.UUID)
	// Place a bid on an auction item
	// (POST /auction/item/{itemID}/bids)
	PostAuctionItemItemIDBids(c *gin.Context, itemID openapi_types.UUID, params PostAuctionItemItemIDBidsParams)
	// Track auction item events
	// (GET /auction/item/{itemID}/events)
	GetAuctionItemItemIDEvents(c *gin.Context, itemID openapi_types.UUID)
	// List auction items
	// (GET /auction/items)
	GetAuctionItems(c *gin.Context, params GetAuctionItemsParams)
	// Exchange authorization code
	// (GET /auth/callback)
	GetAuthCallback(c *gin.Context, params GetAuthCallbackParams)
	// Obtain authentication url
	// (GET /auth/login)
	GetAuthLogin(c *gin.Context, params GetAuthLoginParams)
	// Revoke authentication token
	// (GET /auth/logout)
	GetAuthLogout(c *gin.Context, params GetAuthLogoutParams)
	// Upload an image
	// (POST /image)
	PostImage(c *gin.Context, params PostImageParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAuctionItem operation middleware
func (siw *ServerInterfaceWrapper) PostAuctionItem(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAuctionItemParams

	{
		var cookie string

		if cookie, err = c.Cookie("accessToken"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "accessToken", cookie, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
			if err != nil {
				siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter accessToken: %w", err), http.StatusBadRequest)
				return
			}
			params.AccessToken = &value

		}
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuctionItem(c, params)
}

// GetAuctionItemItemID operation middleware
func (siw *ServerInterfaceWrapper) GetAuctionItemItemID(c *gin.Context) {

	var err error

	// ------------- Path parameter "itemID" -------------
	var itemID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemID", c.Param("itemID"), &itemID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter itemID: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuctionItemItemID(c, itemID)
}

// PostAuctionItemItemIDBids operation middleware
func (siw *ServerInterfaceWrapper) PostAuctionItemItemIDBids(c *gin.Context) {

	var err error

	// ------------- Path parameter "itemID" -------------
	var itemID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemID", c.Param("itemID"), &itemID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter itemID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAuctionItemItemIDBidsParams

	{
		var cookie string

		if cookie, err = c.Cookie("accessToken"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "accessToken", cookie, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
			if err != nil {
				siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter accessToken: %w", err), http.StatusBadRequest)
				return
			}
			params.AccessToken = &value

		}
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuctionItemItemIDBids(c, itemID, params)
}

// GetAuctionItemItemIDEvents operation middleware
func (siw *ServerInterfaceWrapper) GetAuctionItemItemIDEvents(c *gin.Context) {

	var err error

	// ------------- Path parameter "itemID" -------------
	var itemID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemID", c.Param("itemID"), &itemID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter itemID: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuctionItemItemIDEvents(c, itemID)
}

// GetAuctionItems operation middleware
func (siw *ServerInterfaceWrapper) GetAuctionItems(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuctionItemsParams

	// ------------- Optional query parameter "title" -------------

	err = runtime.BindQueryParameter("form", true, false, "title", c.Request.URL.Query(), &params.Title)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter title: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "startPrice" -------------

	err = runtime.BindQueryParameter("deepObject", true, false, "startPrice", c.Request.URL.Query(), &params.StartPrice)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter startPrice: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "currentBid" -------------

	err = runtime.BindQueryParameter("deepObject", true, false, "currentBid", c.Request.URL.Query(), &params.CurrentBid)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter currentBid: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "startTime" -------------

	err = runtime.BindQueryParameter("deepObject", true, false, "startTime", c.Request.URL.Query(), &params.StartTime)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter startTime: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "endTime" -------------

	err = runtime.BindQueryParameter("deepObject", true, false, "endTime", c.Request.URL.Query(), &params.EndTime)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter endTime: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("deepObject", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "lastItemID" -------------

	err = runtime.BindQueryParameter("form", true, false, "lastItemID", c.Request.URL.Query(), &params.LastItemID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter lastItemID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameter("form", true, false, "size", c.Request.URL.Query(), &params.Size)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter size: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "excludeEnded" -------------

	err = runtime.BindQueryParameter("form", true, false, "excludeEnded", c.Request.URL.Query(), &params.ExcludeEnded)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter excludeEnded: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuctionItems(c, params)
}

// GetAuthCallback operation middleware
func (siw *ServerInterfaceWrapper) GetAuthCallback(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthCallbackParams

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument code is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", c.Request.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter code: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument state is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", c.Request.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter state: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "redirect_url" -------------

	if paramValue := c.Query("redirect_url"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument redirect_url is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "redirect_url", c.Request.URL.Query(), &params.RedirectUrl)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter redirect_url: %w", err), http.StatusBadRequest)
		return
	}

	{
		var cookie string

		if cookie, err = c.Cookie("requestState"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "requestState", cookie, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
			if err != nil {
				siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter requestState: %w", err), http.StatusBadRequest)
				return
			}
			params.RequestState = &value

		}
	}

	{
		var cookie string

		if cookie, err = c.Cookie("requestNonce"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "requestNonce", cookie, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
			if err != nil {
				siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter requestNonce: %w", err), http.StatusBadRequest)
				return
			}
			params.RequestNonce = &value

		}
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuthCallback(c, params)
}

// GetAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) GetAuthLogin(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthLoginParams

	// ------------- Required query parameter "redirect_url" -------------

	if paramValue := c.Query("redirect_url"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument redirect_url is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "redirect_url", c.Request.URL.Query(), &params.RedirectUrl)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter redirect_url: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuthLogin(c, params)
}

// GetAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) GetAuthLogout(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthLogoutParams

	{
		var cookie string

		if cookie, err = c.Cookie("accessToken"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "accessToken", cookie, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
			if err != nil {
				siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter accessToken: %w", err), http.StatusBadRequest)
				return
			}
			params.AccessToken = &value

		}
	}

	{
		var cookie string

		if cookie, err = c.Cookie("username"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "username", cookie, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
			if err != nil {
				siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter username: %w", err), http.StatusBadRequest)
				return
			}
			params.Username = &value

		}
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuthLogout(c, params)
}

// PostImage operation middleware
func (siw *ServerInterfaceWrapper) PostImage(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostImageParams

	{
		var cookie string

		if cookie, err = c.Cookie("accessToken"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "accessToken", cookie, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
			if err != nil {
				siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter accessToken: %w", err), http.StatusBadRequest)
				return
			}
			params.AccessToken = &value

		}
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostImage(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auction/item", wrapper.PostAuctionItem)
	router.GET(options.BaseURL+"/auction/item/:itemID", wrapper.GetAuctionItemItemID)
	router.POST(options.BaseURL+"/auction/item/:itemID/bids", wrapper.PostAuctionItemItemIDBids)
	router.GET(options.BaseURL+"/auction/item/:itemID/events", wrapper.GetAuctionItemItemIDEvents)
	router.GET(options.BaseURL+"/auction/items", wrapper.GetAuctionItems)
	router.GET(options.BaseURL+"/auth/callback", wrapper.GetAuthCallback)
	router.GET(options.BaseURL+"/auth/login", wrapper.GetAuthLogin)
	router.GET(options.BaseURL+"/auth/logout", wrapper.GetAuthLogout)
	router.POST(options.BaseURL+"/image", wrapper.PostImage)
}

type PostAuctionItemRequestObject struct {
	Params PostAuctionItemParams
	Body   *PostAuctionItemJSONRequestBody
}

type PostAuctionItemResponseObject interface {
	VisitPostAuctionItemResponse(w http.ResponseWriter) error
}

type PostAuctionItem201ResponseHeaders struct {
	Location string
}

type PostAuctionItem201Response struct {
	Headers PostAuctionItem201ResponseHeaders
}

func (response PostAuctionItem201Response) VisitPostAuctionItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", response.Headers.Location)

	w.WriteHeader(201)
	return nil
}

type PostAuctionItem400JSONResponse ApiResponse

func (response PostAuctionItem400JSONResponse) VisitPostAuctionItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAuctionItem401Response struct {
}

func (response PostAuctionItem401Response) VisitPostAuctionItemResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetAuctionItemItemIDRequestObject struct {
	ItemID openapi_types.UUID `json:"itemID"`
}

type GetAuctionItemItemIDResponseObject interface {
	VisitGetAuctionItemItemIDResponse(w http.ResponseWriter) error
}

type GetAuctionItemItemID200JSONResponse struct {
	BidRecords  []BidEvent `json:"bidRecords"`
	Carousels   []string   `json:"carousels"`
	Description string     `json:"description"`
	EndTime     time.Time  `json:"endTime"`
	StartPrice  int64      `json:"startPrice"`
	StartTime   time.Time  `json:"startTime"`
	Title       string     `json:"title"`
}

func (response GetAuctionItemItemID200JSONResponse) VisitGetAuctionItemItemIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAuctionItemItemID404Response struct {
}

func (response GetAuctionItemItemID404Response) VisitGetAuctionItemItemIDResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PostAuctionItemItemIDBidsRequestObject struct {
	ItemID openapi_types.UUID `json:"itemID"`
	Params PostAuctionItemItemIDBidsParams
	Body   *PostAuctionItemItemIDBidsJSONRequestBody
}

type PostAuctionItemItemIDBidsResponseObject interface {
	VisitPostAuctionItemItemIDBidsResponse(w http.ResponseWriter) error
}

type PostAuctionItemItemIDBids200Response struct {
}

func (response PostAuctionItemItemIDBids200Response) VisitPostAuctionItemItemIDBidsResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PostAuctionItemItemIDBids400JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response PostAuctionItemItemIDBids400JSONResponse) VisitPostAuctionItemItemIDBidsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAuctionItemItemIDBids401Response struct {
}

func (response PostAuctionItemItemIDBids401Response) VisitPostAuctionItemItemIDBidsResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PostAuctionItemItemIDBids403JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response PostAuctionItemItemIDBids403JSONResponse) VisitPostAuctionItemItemIDBidsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostAuctionItemItemIDBids404Response struct {
}

func (response PostAuctionItemItemIDBids404Response) VisitPostAuctionItemItemIDBidsResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PostAuctionItemItemIDBids410JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response PostAuctionItemItemIDBids410JSONResponse) VisitPostAuctionItemItemIDBidsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(410)

	return json.NewEncoder(w).Encode(response)
}

type GetAuctionItemItemIDEventsRequestObject struct {
	ItemID openapi_types.UUID `json:"itemID"`
}

type GetAuctionItemItemIDEventsResponseObject interface {
	VisitGetAuctionItemItemIDEventsResponse(w http.ResponseWriter) error
}

type GetAuctionItemItemIDEvents200Response struct {
}

func (response GetAuctionItemItemIDEvents200Response) VisitGetAuctionItemItemIDEventsResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetAuctionItemItemIDEvents403JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response GetAuctionItemItemIDEvents403JSONResponse) VisitGetAuctionItemItemIDEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetAuctionItemItemIDEvents404Response struct {
}

func (response GetAuctionItemItemIDEvents404Response) VisitGetAuctionItemItemIDEventsResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetAuctionItemItemIDEvents410JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response GetAuctionItemItemIDEvents410JSONResponse) VisitGetAuctionItemItemIDEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(410)

	return json.NewEncoder(w).Encode(response)
}

type GetAuctionItemsRequestObject struct {
	Params GetAuctionItemsParams
}

type GetAuctionItemsResponseObject interface {
	VisitGetAuctionItemsResponse(w http.ResponseWriter) error
}

type GetAuctionItems200JSONResponse struct {
	Count int `json:"count"`
	Items []struct {
		CurrentBid uint32             `json:"currentBid"`
		EndTime    time.Time          `json:"endTime"`
		Id         openapi_types.UUID `json:"id"`
		IsEnded    bool               `json:"isEnded"`
		StartTime  time.Time          `json:"startTime"`
		Title      string             `json:"title"`
	} `json:"items"`
}

func (response GetAuctionItems200JSONResponse) VisitGetAuctionItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAuctionItems400JSONResponse ApiResponse

func (response GetAuctionItems400JSONResponse) VisitGetAuctionItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAuctionItems404Response struct {
}

func (response GetAuctionItems404Response) VisitGetAuctionItemsResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetAuthCallbackRequestObject struct {
	Params GetAuthCallbackParams
}

type GetAuthCallbackResponseObject interface {
	VisitGetAuthCallbackResponse(w http.ResponseWriter) error
}

type GetAuthCallback200ResponseHeaders struct {
	Location                                      string
	SetCookieAccessTokenHttpOnlySecureMaxAge10800 string
	SetCookieUsernameMaxAge10800                  string
	UnsetCookieRequestNonceHttpOnlySecure         string
	UnsetCookieRequestStateHttpOnlySecure         string
}

type GetAuthCallback200Response struct {
	Headers GetAuthCallback200ResponseHeaders
}

func (response GetAuthCallback200Response) VisitGetAuthCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", response.Headers.Location)

	http.SetCookie(w, &http.Cookie{
		Name:     "accessToken",
		Value:    response.Headers.SetCookieAccessTokenHttpOnlySecureMaxAge10800,
		Secure:   true,
		HttpOnly: true,
		Path:     "/",
		SameSite: http.SameSiteStrictMode,
		MaxAge:   10800,
	})

	http.SetCookie(w, &http.Cookie{
		Name:     "username",
		Value:    response.Headers.SetCookieUsernameMaxAge10800,
		Secure:   false,
		HttpOnly: false,
		Path:     "/",
		SameSite: http.SameSiteStrictMode,
		MaxAge:   10800,
	})

	http.SetCookie(w, &http.Cookie{
		Name:     "requestNonce",
		Value:    "", // 清空 cookie
		Secure:   true,
		HttpOnly: true,
		Path:     "/",
		SameSite: http.SameSiteStrictMode,
		Expires:  time.Unix(0, 0),
	})

	http.SetCookie(w, &http.Cookie{
		Name:     "requestState",
		Value:    "", // 清空 cookie
		Secure:   true,
		HttpOnly: true,
		Path:     "/",
		SameSite: http.SameSiteStrictMode,
		Expires:  time.Unix(0, 0),
	})
	w.WriteHeader(200)
	return nil
}

type GetAuthLoginRequestObject struct {
	Params GetAuthLoginParams
}

type GetAuthLoginResponseObject interface {
	VisitGetAuthLoginResponse(w http.ResponseWriter) error
}

type GetAuthLogin200ResponseHeaders struct {
	Location                                     string
	SetCookieRequestNonceHttpOnlySecureMaxAge120 string
	SetCookieRequestStateHttpOnlySecureMaxAge120 string
}

type GetAuthLogin200Response struct {
	Headers GetAuthLogin200ResponseHeaders
}

func (response GetAuthLogin200Response) VisitGetAuthLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", response.Headers.Location)

	http.SetCookie(w, &http.Cookie{
		Name:     "requestNonce",
		Value:    response.Headers.SetCookieRequestNonceHttpOnlySecureMaxAge120,
		Secure:   true,
		HttpOnly: true,
		Path:     "/",
		SameSite: http.SameSiteStrictMode,
		MaxAge:   120,
	})

	http.SetCookie(w, &http.Cookie{
		Name:     "requestState",
		Value:    response.Headers.SetCookieRequestStateHttpOnlySecureMaxAge120,
		Secure:   true,
		HttpOnly: true,
		Path:     "/",
		SameSite: http.SameSiteStrictMode,
		MaxAge:   120,
	})
	w.WriteHeader(200)
	return nil
}

type GetAuthLogoutRequestObject struct {
	Params GetAuthLogoutParams
}

type GetAuthLogoutResponseObject interface {
	VisitGetAuthLogoutResponse(w http.ResponseWriter) error
}

type GetAuthLogout200ResponseHeaders struct {
	UnsetCookieAccessTokenHttpOnlySecure string
	UnsetCookieUsernameHttpOnlySecure    string
}

type GetAuthLogout200Response struct {
	Headers GetAuthLogout200ResponseHeaders
}

func (response GetAuthLogout200Response) VisitGetAuthLogoutResponse(w http.ResponseWriter) error {

	http.SetCookie(w, &http.Cookie{
		Name:     "accessToken",
		Value:    "", // 清空 cookie
		Secure:   true,
		HttpOnly: true,
		Path:     "/",
		SameSite: http.SameSiteStrictMode,
		Expires:  time.Unix(0, 0),
	})

	http.SetCookie(w, &http.Cookie{
		Name:     "username",
		Value:    "", // 清空 cookie
		Secure:   true,
		HttpOnly: true,
		Path:     "/",
		SameSite: http.SameSiteStrictMode,
		Expires:  time.Unix(0, 0),
	})
	w.WriteHeader(200)
	return nil
}

type PostImageRequestObject struct {
	Params PostImageParams
	Body   io.Reader
}

type PostImageResponseObject interface {
	VisitPostImageResponse(w http.ResponseWriter) error
}

type PostImage201ResponseHeaders struct {
	Location string
}

type PostImage201Response struct {
	Headers PostImage201ResponseHeaders
}

func (response PostImage201Response) VisitPostImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", response.Headers.Location)

	w.WriteHeader(201)
	return nil
}

type PostImage400JSONResponse ApiResponse

func (response PostImage400JSONResponse) VisitPostImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostImage401Response struct {
}

func (response PostImage401Response) VisitPostImageResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PostImage429Response struct {
}

func (response PostImage429Response) VisitPostImageResponse(w http.ResponseWriter) error {
	w.WriteHeader(429)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Add a new auction item
	// (POST /auction/item)
	PostAuctionItem(ctx context.Context, request PostAuctionItemRequestObject) (PostAuctionItemResponseObject, error)
	// Get auction item details
	// (GET /auction/item/{itemID})
	GetAuctionItemItemID(ctx context.Context, request GetAuctionItemItemIDRequestObject) (GetAuctionItemItemIDResponseObject, error)
	// Place a bid on an auction item
	// (POST /auction/item/{itemID}/bids)
	PostAuctionItemItemIDBids(ctx context.Context, request PostAuctionItemItemIDBidsRequestObject) (PostAuctionItemItemIDBidsResponseObject, error)
	// Track auction item events
	// (GET /auction/item/{itemID}/events)
	GetAuctionItemItemIDEvents(ctx context.Context, request GetAuctionItemItemIDEventsRequestObject) (GetAuctionItemItemIDEventsResponseObject, error)
	// List auction items
	// (GET /auction/items)
	GetAuctionItems(ctx context.Context, request GetAuctionItemsRequestObject) (GetAuctionItemsResponseObject, error)
	// Exchange authorization code
	// (GET /auth/callback)
	GetAuthCallback(ctx context.Context, request GetAuthCallbackRequestObject) (GetAuthCallbackResponseObject, error)
	// Obtain authentication url
	// (GET /auth/login)
	GetAuthLogin(ctx context.Context, request GetAuthLoginRequestObject) (GetAuthLoginResponseObject, error)
	// Revoke authentication token
	// (GET /auth/logout)
	GetAuthLogout(ctx context.Context, request GetAuthLogoutRequestObject) (GetAuthLogoutResponseObject, error)
	// Upload an image
	// (POST /image)
	PostImage(ctx context.Context, request PostImageRequestObject) (PostImageResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PostAuctionItem operation middleware
func (sh *strictHandler) PostAuctionItem(ctx *gin.Context, params PostAuctionItemParams) {
	var request PostAuctionItemRequestObject

	request.Params = params

	var body PostAuctionItemJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuctionItem(ctx, request.(PostAuctionItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuctionItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostAuctionItemResponseObject); ok {
		if err := validResponse.VisitPostAuctionItemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuctionItemItemID operation middleware
func (sh *strictHandler) GetAuctionItemItemID(ctx *gin.Context, itemID openapi_types.UUID) {
	var request GetAuctionItemItemIDRequestObject

	request.ItemID = itemID

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuctionItemItemID(ctx, request.(GetAuctionItemItemIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuctionItemItemID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAuctionItemItemIDResponseObject); ok {
		if err := validResponse.VisitGetAuctionItemItemIDResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuctionItemItemIDBids operation middleware
func (sh *strictHandler) PostAuctionItemItemIDBids(ctx *gin.Context, itemID openapi_types.UUID, params PostAuctionItemItemIDBidsParams) {
	var request PostAuctionItemItemIDBidsRequestObject

	request.ItemID = itemID
	request.Params = params

	var body PostAuctionItemItemIDBidsJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuctionItemItemIDBids(ctx, request.(PostAuctionItemItemIDBidsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuctionItemItemIDBids")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostAuctionItemItemIDBidsResponseObject); ok {
		if err := validResponse.VisitPostAuctionItemItemIDBidsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuctionItemItemIDEvents operation middleware
func (sh *strictHandler) GetAuctionItemItemIDEvents(ctx *gin.Context, itemID openapi_types.UUID) {
	var request GetAuctionItemItemIDEventsRequestObject

	request.ItemID = itemID

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuctionItemItemIDEvents(ctx, request.(GetAuctionItemItemIDEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuctionItemItemIDEvents")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAuctionItemItemIDEventsResponseObject); ok {
		if err := validResponse.VisitGetAuctionItemItemIDEventsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuctionItems operation middleware
func (sh *strictHandler) GetAuctionItems(ctx *gin.Context, params GetAuctionItemsParams) {
	var request GetAuctionItemsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuctionItems(ctx, request.(GetAuctionItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuctionItems")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAuctionItemsResponseObject); ok {
		if err := validResponse.VisitGetAuctionItemsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthCallback operation middleware
func (sh *strictHandler) GetAuthCallback(ctx *gin.Context, params GetAuthCallbackParams) {
	var request GetAuthCallbackRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthCallback(ctx, request.(GetAuthCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthCallback")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAuthCallbackResponseObject); ok {
		if err := validResponse.VisitGetAuthCallbackResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthLogin operation middleware
func (sh *strictHandler) GetAuthLogin(ctx *gin.Context, params GetAuthLoginParams) {
	var request GetAuthLoginRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthLogin(ctx, request.(GetAuthLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAuthLoginResponseObject); ok {
		if err := validResponse.VisitGetAuthLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthLogout operation middleware
func (sh *strictHandler) GetAuthLogout(ctx *gin.Context, params GetAuthLogoutParams) {
	var request GetAuthLogoutRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthLogout(ctx, request.(GetAuthLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthLogout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAuthLogoutResponseObject); ok {
		if err := validResponse.VisitGetAuthLogoutResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostImage operation middleware
func (sh *strictHandler) PostImage(ctx *gin.Context, params PostImageParams) {
	var request PostImageRequestObject

	request.Params = params

	request.Body = ctx.Request.Body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostImage(ctx, request.(PostImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostImageResponseObject); ok {
		if err := validResponse.VisitPostImageResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/bOBL+KwTvPqq20wR7ty7yIWmDXhbtNqhTXIEiWNDi2OZGIrUk5dqb5r8fhtSr",
	"JdmynV63xQabbSxT5Lw888yL9EBDFSdKgrSGjh+oCRcQM/fnRSLeg0mUNIAfE60S0FaA+zJU3F2dKR0z",
	"S8dUSHv6nAbUrhPwH2EOmj4GNAZj2Nytzr40Vgs5p4+PxXI1/R1Ci6svBb9agrTNI6eC105Mu4+0Iq5L",
	"x5mFZ+5qsClEQFMDul06DX+kQgOn409+VeCkyA64a4iP9wg5U7gbBxNqkVihJB3Ti5trMlOaxEyyuZBz",
	"wiQnCdNWhCJhFq8ISZgkLA3xFmLWxkI8cGfZCA+5yL65uLmmAV2CNn7rk8FoMEI9VAKSJYKO6elgNDil",
	"AU2YXTjbDbNth8JC7EyrjG1K+VIDs0AYkfC5kERkcqAvGF655nRMb5SxmUTXuCceplkMFrSh40+bO7Mw",
	"BGOIVfcgnSHCVGuQlqBZcXeBq0Kl7gX6SDJ0YHbXLd5EgwybKDWsWJw4o6xWq8HK/fh/mv59vPN+BGMv",
	"FV978EqbQYwlSSRCp9bwd4OiPlTO2cA80yo1ELkPaBVTx6MWbejKLjCt2Ro/1+zy0FwPkt/uBV9jmbYH",
	"3CLk/EaLsBHGP511xJSD4a4w8ctKNdqDpLzD6hTcBc80zqTPRydNbCLKSOgAyolJHTJmaRStET0LYNwB",
	"74G+Ud6dzR1uF0Ci7FuiZsQuoNgwB3np++1+dVqcjUZ7wemfGmZ0TP8xLDl3mBHusMq2bvMN7eWSRYIT",
	"ziwjiVZLwYEPqBOixVgfJEvtQmnxJ3Dio2jgXGXSOGZ6jXTCeUugo6ZsjhGc8w29w/tqBDJ8wP9fv3rE",
	"g+fQQiTvwWoBSyAcLBORQXMzYhIIxUyEO6jlNVSZxf2+avKLIwwkuJIuRL60Dq92r6aeyNvIogbF0RGM",
	"MRX8PYRK8zplbMNBkf9aqOOvTED7UMkBjLUn+1R1rAkYVH0S0CwLXToslGKVRqgavZ3K6sCfFMREtI8B",
	"FiH40Vt5MGRhe9bBcVJZMlOp5JsR+xpsLXLy/faL2eFUeDi2lwCTdBoLSxiZCu4Sde+w3agIfNxeCmfn",
	"/0vsBj9i0dG76t2IBLzvsNw7aoLiUnCSRCxsZN4DkmBdvX2ag2a0oVxWKRKpz/vmQlx8+s0Ez2t5jHVH",
	"O8DJGuwezBDQs5PRN5d/wQwB6UsR5CoIUy3s2gX5FJgGfZHaBR1/usOIKKnsBsGUkYyq9T37FyFDWObd",
	"a2stMrEaWIxHcWyz/Opt1EZSgwsnk6t+tcmVP//bViidaShUUoJXzipUihhnkL9j4CvFQAHyW83C+zqy",
	"IIfKbnyb3cV1dWtDPgu7IMotYhGZiQiB6OYMRrlubxeaza4mfgJMhwtiQccufvwZbnaBtxcZ9Y8U9LoE",
	"fV6UlW7YmbknWYNKEqzaiGZyDvscWav4utw/0yquSFPtdVXb9bZxlbFrVxJwgORdfrUxVsnKDmS7vVWp",
	"l6jfWhXsoYsRFRqZYMV+oIOyCnuXUj07BNV37ZMoD5IfqHrZWnw3ik+UtiTUAtVjnS5V2m5R6h7Wnspm",
	"LI1shRZApnG1d6vF7s4G7a7FIkpzP9EtD2MmrBzlP6GOLfcfBY+IGeup/vpVPmNKNCyFSg1J2By6rIc3",
	"FqOOI3oeFCJmKxGnMZFpPAWdt5/YCGFTmmrZ6ULxZx2XhQFPgl4tyKY0V6swSjn4/LgjLPzSK1zZLsOM",
	"RQaKU6dKRcDkk89sQpX6m5pcWqTl4o+NW0uw9nxQsfesZXPrVlQEVBhvx1KNwlxfc/ySPRvxcdxjtpKL",
	"edcScvWx1cZB3km5R44dzJiDGtkjprlvhXEtRlltdVe9v6oseltnQm+EqQ+FthWXdjEMWRRNWXjfWVxe",
	"rcKFy2h50+zH5aHigPwxE1KYhfsSpM2MQ2aR+uwqTQ1caAgtLlVazIUsSK+l8rSLl7k4uypPqzR27/Vj",
	"jWUWOuc42fxlgos6BjnG/rYqfvqwa7scUslwpxy/4qIOOeSeYlw0fNNZPSoOW9vNPc+qm7xZ1NkjT/ug",
	"I8TO1HVOMws6Q5x7ZFqVpEuGHIG/pTrq2We3Pt/p1WZfbODxqZ5KVUKHTGGmNC6ZC7nXE6qATsA+e+nQ",
	"+KUy1PzyH2uTdzJav5hAmGp48Zatnl3M4fxk9O9WJXk+NssmqUJaRdyoB8jC2oQoGa2Jh/2gA+GlKKQi",
	"ynk2QsXfF6SQi2SCkVyy059GI1qpQH757+0uhVMDGiHxpYd2+dqaZtv1yW85//jx48dOgZsSfpCmlLHK",
	"DJteaWv7Y7WEVu4h2DEc4RK3yXmbB65WidBgzm8XaUBGJ+QXJsnJz/8akdFo7P4jr9/e9tbUcfGhmjp2",
	"OVZTt8mTavpYT8hb8mctM1dVqyZoF+ed2fnd1DIhNy2T6qiWfTvT7Ru3+Y5c+31R8K2nJGPSp3wtwHnB",
	"86+aNYAIeumfHx3GxdvCviTj511U3Bb/R1Kyj//9yLiPiq3xvreKPvCPVNEH/nEqboR6ZzD2DXSV2i1D",
	"3qW6h1ri3RbWuNVf9xWsRpnnsm1vGfJk2y3Atqew/RhEO3tvpZBaRttSUHUntJoHDkhk1dLpmBy2s5Cq",
	"qVqUUn31LOqpqo4966mvmJrzkKrHq82gvTViRZw9J2p/aeJDEinGCZPELSQzEUH7CxLXbqMf4GVJFVqw",
	"z/yjxPpcpADXVEjm6oKGXw57AdCZNnWmfspcX+zofPfDvwQY0LPnP7exoCIxk2uSub/xvuAGxisR4zF9",
	"5wTOrjWmSpInSuTP3cuXoKuDqyB/RB+4YtZqFt5XF/lnp4MS8Pl4q2XsXDsOo2Yz6vGERjFb7FtjgF3b",
	"F9o4u1QF9IZ5vHv8XwAAAP//0poqQGYvAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
