name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      context:
        required: false
        default: "."
        type: string
      dockerfile:
        required: true
        type: string
      image:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.Q4_PACKAGE_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platform }}
          provenance: false
          push: true
          tags: |
            ${{ inputs.image }}:${{ github.ref_name }}
            ${{ inputs.image }}:latest
